# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Turbulent Dynamics
email: niall@turbulentdynamics.com
description: >- # Turbulent Dynamics uses in-house technology to deliver 60% 
reduction in costs with high performance computing and machine learning for 
high-resolution turbulent aerodynamics research and visualisation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://turbulentdynamics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: turbulentdynam
github_username:  turbulentdynamics

# Build settings
markdown: kramdown
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
#plugins:
#  - jekyll-feed

include: ["_pages"]




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/





minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "en-UK"
title_separator: "|"
repository: "TurbulentDynamics/TurbulentDynamics.github.io"


author:
  name     : "Turbulent Dynamics"
  #avatar   : "/assets/images/bio-photo.jpg"
  #bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Dublin, Zagreb, San Francisco, Melbourne" 


header:
    


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/turbulentdynam"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TurbulentDynamics/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: false
